project_id = "mrouohttlvirnvmdmwqj"

[functions.custom-login]
verify_jwt = false

[functions.verify-session]
verify_jwt = false

[functions.data-access]
verify_jwt = false

[functions.ensure-public-user]
verify_jwt = false

[functions.update-account]
verify_jwt = false

[functions.microsoft-login]
verify_jwt = false

[functions.microsoft-callback]
verify_jwt = false

[functions.microsoft-status]
verify_jwt = false

[functions.microsoft-disconnect]
verify_jwt = false

[functions.get-calendar-events]
verify_jwt = false
