project_id = "mrouohttlvirnvmdmwqj"

[functions.custom-login]
verify_jwt = false

[functions.verify-session]
verify_jwt = false

[functions.data-access]
verify_jwt = false

[functions.ensure-public-user]
verify_jwt = false
